version: '3.8'

services:
  springboot:
    image: givanc/test-cicd:latest
    restart: always
    networks:
      - TestCICD
    ports:
      - ${PORT_APP}:8080
networks:
  TestCICD:
    external: true

